name: tentaclesv
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  # Core pipeline requirements
  - python=3.10
  - snakemake-minimal=7.32.4
  - pandas=2.1.1
  
  # Python dependencies for utility scripts
  - pysam=0.21.0
  - numpy=1.24.3
  - matplotlib=3.7.2
  - scipy=1.11.3
  - click=8.1.7
  - biopython=1.81
  
  # Mapping tools
  - bwa-mem2=2.2.1
  - minimap2=2.26
  - samtools=1.17
  
  # Short-read SV callers
  - manta=1.6.0
  - delly=1.1.6
  - lumpy-sv=0.3.1
  - svaba=1.1.0
  
  # Long-read SV callers
  - cutesv=2.0.3
  - pbsv=2.9.0
  - sniffles=2.0.7
  - svim=2.0.0
  - svdss=0.2.0
  - debreak=1.3
  
  # Additional tools
  - bcftools=1.17
  - htslib=1.17
  - bedtools=2.31.0
  - pip>=23.0

  # Install local octopusV
  - pip:
    - -e /home/qgn1237/2_software/SVmerger
