# Detailed parameters for each SV caller

manta:
  # Manta specific parameters
  min_candidate_spanning_count: 3
  min_candidate_size: 8
  min_scored_size: 50
  timeout_minutes: 60
  memory_gb: 16

delly:
  # Delly specific parameters
  min_mapping_quality: 20
  min_paired_end_support: 4
  max_insert_size: 15000
  min_size: 50
  timeout_minutes: 120

lumpy:
  # Lumpy specific parameters
  read_length: 150  # Added based on our data
  min_non_overlap: 150
  discordant_z: 4
  back_distance: 20
  weight: 1
  min_mapping_threshold: 20
  min_clip_length: 20
  min_sample_weight: 4  # Minimum sample weight for a call
  trim_threshold: 0     # Trim threshold for noise reduction

svaba:
  # SvABA specific parameters
  germline_mode: true
  min_reads: 2
  min_size: 50
  max_size: 1000000

cutesv:
  # CuteSV specific parameters
  min_support: 2
  min_size: 50
  max_size: 5000000
  min_mapq: 20
  signal_distance: 1000
  diff_ratio_merging_ins: 0.9
  diff_ratio_merging_del: 0.5

sniffles:
  # Sniffles specific parameters
  min_support: "auto"
  min_length: 50
  max_num_splits: 7
  max_distance: 50
  min_alignment_length: 1000
  min_seq_size: 1000

svim:
  # SVIM specific parameters
  min_mapq: 20
  min_sv_size: 50
  max_sv_size: 100000
  min_read_length: 1000
  segment_gap_tolerance: 10
  segment_overlap_tolerance: 5
  partition_max_distance: 1000

pbsv:
  # PBSV specific parameters
  min_read_length: 1000
  min_confidence: 10
  min_ref_span: 50
  min_sv_length: 50

debreak:
  # Debreak specific parameters
  min_support: 2
  min_size: 50
  rescue_large_ins: true
  rescue_dup: true
  use_poa: true

svdss:
  # SVDSS specific parameters
  smooth:
    threads: 6
  search:
    threads: 6
  call:
    min_support: 2
    min_size: 50
