# General settings
seq_type: "short"  # Changed to short for NGS data
threads: 12

# Reference genome settings (keeping the same as long-read config)
reference:
  fasta: "/projects/b1171/qgn1237/1_my_database/GRCh38_p13/GRCh38.p13.genome.fa"
  minimap2_index: "/projects/b1171/qgn1237/1_my_database/GRCh38_p13/minimap2_index/GRCh38.p13.genome.mmi"
  tandem_repeats: "/projects/b1171/qgn1237/1_my_database/GRCh38_p13/tandem_repeats/human_GRCh38_no_alt_analysis_set.trf.bed"
  # Add BWA-MEM2 index path if available
  bwa_index: "/projects/b1171/qgn1237/1_my_database/GRCh38_p13/GRCh38.p13.genome"

# Input samples
samples:
  test_sample:
    type: "paired"  # Changed to paired for paired-end reads
    fq1: "/projects/b1171/qgn1237/6_SV_VCF_merger/20241113_octopusv_final_benchmarking/Simulation_data/NGS_simulated_100VAF/NGS_fastq/subset_r1.fq"
    fq2: "/projects/b1171/qgn1237/6_SV_VCF_merger/20241113_octopusv_final_benchmarking/Simulation_data/NGS_simulated_100VAF/NGS_fastq/subset_r2.fq"
    platform: "illumina"  # Changed to illumina for short reads

# Container settings
containers:
  manta: "containers/images/manta.sif"
  lumpy: "containers/images/lumpy-sv.sif"
  debreak: "containers/images/debreak.sif"

# SV callers selection
callers:
  short_read:  # Updated callers for short-read data
    - "manta"
    - "delly"
    - "lumpy"
    - "svaba"

# Mapping parameters (keeping both short and long read parameters)
mapping:
  short_read:
    tool: "bwa-mem2"
    extra_params: "-M -Y"
  long_read_ont:
    tool: "minimap2"
    preset: "map-ont"
    extra_params: "--MD -Y"
  long_read_pacbio:
    tool: "minimap2"
    preset: "map-hifi"
    extra_params: "--MD -Y"

# BAM processing
bam_processing:
  remove_duplicates: true
  min_mapping_quality: 20
  filter_supplementary: true

# OctopusV parameters (keeping the same)
octopusv:
  correct:
    pos_tolerance: 3
  merge:
    min_support: 2
    max_distance: 50
    max_length_ratio: 1.3
    min_jaccard: 0.7
    tra_delta: 50
    tra_min_overlap: 0.5
    tra_strand_consistency: true

# Output settings (keeping the same)
output:
  directory: "results"
  cleanup_intermediates: true
  generate_reports: true
  upset_plot: true


# Detailed parameters for each SV caller
# Manta parameters
manta:
  min_candidate_spanning_count: 3
  min_candidate_size: 8
  min_scored_size: 50
  timeout_minutes: 60
  memory_gb: 16

# Delly parameters
delly:
  min_mapping_quality: 20
  min_paired_end_support: 4
  max_insert_size: 15000
  min_size: 50
  timeout_minutes: 120

# SvABA parameters
svaba:
  min_reads: 2
  min_size: 50
  max_size: 1000000

# CuteSV parameters
cutesv:
  min_support: 2
  min_size: 50
  max_size: 5000000
  min_mapq: 20
  signal_distance: 1000
  diff_ratio_merging_ins: 0.9
  diff_ratio_merging_del: 0.5

# Sniffles parameters
sniffles:
  min_support: "auto"
  min_length: 50
  max_num_splits: 7
  max_distance: 50
  min_alignment_length: 1000
  min_seq_size: 1000

# SVIM parameters
svim:
  min_mapq: 20
  min_sv_size: 50
  max_sv_size: 100000
  min_read_length: 1000
  segment_gap_tolerance: 10
  segment_overlap_tolerance: 5
  partition_max_distance: 1000

# PBSV parameters
pbsv:
  min_read_length: 1000
  min_confidence: 10
  min_ref_span: 50
  min_sv_length: 50

# Debreak parameters
debreak:
  min_support: 2
  min_size: 50
  rescue_large_ins: true
  rescue_dup: true
  use_poa: true

# SVDSS parameters
svdss:
  smooth:
    threads: 6
  search:
    threads: 6
  call:
    min_support: 2
    min_size: 50
