# General settings
seq_type: "short"  # Sequencing type: "short", "long_ont", or "long_pacbio"
threads: 8         # Default number of threads for parallel processing
memory_gb: 16      # Default memory allocation in GB

# Reference genome settings
reference:
  fasta: "path/to/reference.fa"
  index: "path/to/reference.index"
  tandem_repeats: "path/to/tandem_repeats.bed"  # Required for some callers

# Input samples configuration
samples:
  sample1:
    type: "paired"  # paired, single, or bam
    fq1: "data/sample1_R1.fq.gz"
    fq2: "data/sample1_R2.fq.gz"
    platform: "illumina"
  sample2:
    type: "bam"
    bam: "data/sample2.bam"
    platform: "pacbio"

# SV callers selection
callers:
  short_read:
    - "manta"
    - "delly"
    - "lumpy"
    - "svaba"
  long_read_ont:
    - "cutesv"
    - "sniffles2"
    - "svim"
    - "svdss"
  long_read_pacbio:
    - "cutesv"
    - "pbsv"
    - "sniffles2"
    - "svim"
    - "debreak"
    - "svdss"

# Mapping parameters
mapping:
  short_read:
    tool: "bwa-mem2"
    extra_params: "-M -Y"
  long_read_ont:
    tool: "minimap2"
    preset: "map-ont"
    extra_params: "--MD -Y"
  long_read_pacbio:
    tool: "minimap2"
    preset: "map-hifi"
    extra_params: "--MD -Y"

# BAM processing
bam_processing:
  remove_duplicates: true
  min_mapping_quality: 20
  filter_supplementary: true

# OctopusV parameters
octopusv:
  correct:
    pos_tolerance: 3
  merge:
    min_support: 2
    max_distance: 50
    max_length_ratio: 1.3
    min_jaccard: 0.7
    tra_delta: 50
    tra_min_overlap: 0.5
    tra_strand_consistency: true

# Output settings
output:
  directory: "results"
  cleanup_intermediates: true
  generate_reports: true
  upset_plot: true
