#--------------------
# General settings
#--------------------
seq_type: "short"  # Options: "short", "long_pacbio", "long_ont"
threads: 12

#--------------------
# Reference genome settings
#--------------------
reference:
  fasta: "/path/to/reference/genome.fa"
  # For short reads
  bwa_index: "/path/to/bwa/index/genome"
  # For long reads
  minimap2_index: "/path/to/minimap2/genome.mmi"
  tandem_repeats: "/path/to/tandem_repeats.bed"

#--------------------
# Input samples
#--------------------
samples:
  # Example for paired-end short reads
  sample1:
    type: "fastq"
    fq1: "/path/to/sample1_R1.fastq.gz"
    fq2: "/path/to/sample1_R2.fastq.gz"
    platform: "illumina"
    
  # Example for long reads
  sample2:
    type: "fastq"
    fq1: "/path/to/sample2.fastq.gz"
    platform: "pacbio"  # or "ont"
    
  # Example for pre-aligned BAM
  sample3:
    type: "bam"
    bam: "/path/to/aligned.bam"
    platform: "illumina"  # or "pacbio" or "ont"

#--------------------
# Container settings
#--------------------
containers:
  lumpy: "containers/images/lumpy-sv.sif"
  debreak: "containers/images/debreak.sif"

#--------------------
# SV caller selection
#--------------------
callers:
  short_read:
    - "manta"
    - "delly"
    - "lumpy"
    - "svaba"
  long_read_pacbio:
    - "cutesv"
    - "sniffles"
    - "svim"
    - "pbsv"
    - "debreak"
    - "svdss"
  long_read_ont:
    - "cutesv"
    - "sniffles"
    - "svim"
    - "debreak"
    - "svdss"

#--------------------
# Mapping parameters
#--------------------
mapping:
  short_read:
    tool: "bwa-mem2"
    extra_params: "-M -Y"
  long_read_ont:
    tool: "minimap2"
    preset: "map-ont"
    extra_params: "--MD -Y"
  long_read_pacbio:
    tool: "minimap2"
    preset: "map-hifi"
    extra_params: "--MD -Y"

#--------------------
# BAM processing
#--------------------
bam_processing:
  remove_duplicates: true
  min_mapping_quality: 20
  filter_supplementary: true

#--------------------
# OctopusV parameters
#--------------------
octopusv:
  correct:
    pos_tolerance: 3
  merge:
    min_support: 2
    max_distance: 50
    max_length_ratio: 1.3
    min_jaccard: 0.7
    tra_delta: 50
    tra_min_overlap: 0.5
    tra_strand_consistency: true

#--------------------
# Output settings
#--------------------
output:
  directory: "results"
  cleanup_intermediates: true
  generate_reports: true
  upset_plot: true

#--------------------
# Caller-specific parameters
#--------------------
# Manta parameters
manta:
  bin_path: "tools/manta/manta-1.6.0.centos6_x86_64/bin"

# Delly parameters
delly:
  min_mapping_quality: 20
  min_paired_end_support: 4
  max_insert_size: 15000
  min_size: 50
  timeout_minutes: 120

# SvABA parameters
svaba:
  min_reads: 2
  min_size: 50
  max_size: 1000000

# CuteSV parameters
cutesv:
  min_support: 2
  min_size: 50
  max_size: 5000000
  min_mapq: 20
  signal_distance: 1000
  diff_ratio_merging_ins: 0.9
  diff_ratio_merging_del: 0.5

# Sniffles parameters
sniffles:
  min_support: "auto"
  min_length: 50
  max_num_splits: 7
  max_distance: 50
  min_alignment_length: 1000
  min_seq_size: 1000

# SVIM parameters
svim:
  min_mapq: 20
  min_sv_size: 50
  max_sv_size: 100000
  min_read_length: 1000
  segment_gap_tolerance: 10
  segment_overlap_tolerance: 5
  partition_max_distance: 1000

# PBSV parameters
pbsv:
  min_read_length: 1000
  min_confidence: 10
  min_ref_span: 50
  min_sv_length: 50

# Debreak parameters
debreak:
  min_support: 2
  min_size: 50
  rescue_large_ins: true
  rescue_dup: true
  use_poa: true

# SVDSS parameters
svdss:
  smooth:
    threads: 6
  search:
    threads: 6
  call:
    min_support: 2
    min_size: 50
